'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {requestJson} from '@/lib/v2-http';
type State={complete:boolean;platformRole:string;resources:Record<string,number>};
const labels={name:'Organization name',taxId:'Tax ID',city:'City',governorate:'Governorate',address:'Operating address',phone:'Contact phone'};
export default function Onboarding(){const [s,setS]=useState<State|null>(null),[form,setForm]=useState({name:'',taxId:'',city:'',governorate:'',address:'',phone:''}),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
useEffect(()=>{let active=true;requestJson<State>('/api/v2/onboarding').then(x=>{if(active)setS(x)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);
async function save(e:React.FormEvent){e.preventDefault();setBusy(true);try{await requestJson('/api/v2/onboarding',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});setS(await requestJson<State>('/api/v2/onboarding'));setMessage('Organization profile connected.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
return <><div className="eyebrow">Organization profile</div><h1>Start with your business.</h1><p className="muted">Connect your operating identity to the workspace. Supplier listings become available after administrator verification.</p>{error?<div className="workspace-status" role="alert">{error} <button className="btn btn-ghost" onClick={()=>window.location.reload()}>Retry</button></div>:!s?<p role="status">Loading organization profile…</p>:<section className="card" style={{maxWidth:760,padding:26,marginTop:28}}><div className="eyebrow">{s.platformRole}</div><h2>{s.complete?'Profile connected':'Required business details'}</h2>{s.complete?<Link href="/dashboard" className="btn btn-blue">Continue to workspace</Link>:<form onSubmit={save}><div className="workspace-form">{(Object.keys(labels) as Array<keyof typeof labels>).map(k=><label key={k}>{labels[k]}<input required={['name','city','governorate'].includes(k)||(k==='taxId'&&s.platformRole!=='SHIPPING')} autoComplete={k==='phone'?'tel':k==='address'?'street-address':undefined} type={k==='phone'?'tel':'text'} maxLength={160} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}</div><button className="btn btn-blue" disabled={busy} style={{marginTop:20}}>{busy?'Connecting…':'Connect organization'}</button></form>}{message&&<p role="status">{message}</p>}</section>}</>}
