import { NextResponse } from 'next/server';
import { z } from 'zod';
import { Prisma } from '@prisma/client';
import { prisma } from '@/lib/prisma';
import { getActor } from '@/lib/v2-auth';
import { appendAuditEntry } from '@/lib/audit/tamper-proof';
const item=z.object({name:z.string().trim().min(2).max(160),sku:z.string().trim().min(2).max(80),category:z.enum(['F_AND_B','CONSUMABLES','GUEST_SUPPLIES','FFE','SERVICES']),unitOfMeasure:z.string().trim().min(1).max(30),unitPrice:z.number().finite().positive().max(10000000).nullable(),stockQuantity:z.number().int().min(0).max(10000000)});
export async function GET(){const u=await getActor();if(!u)return NextResponse.json({error:'UNAUTHENTICATED'},{status:401});if(u.platformRole!=='SUPPLIER'||!u.supplierId)return NextResponse.json({error:'Complete your supplier profile first'},{status:403});const [supplier,products]=await Promise.all([prisma.supplier.findFirst({where:{id:u.supplierId,tenantId:u.tenantId,deletedAt:null},select:{isVerified:true,status:true}}),prisma.product.findMany({where:{supplierId:u.supplierId,tenantId:u.tenantId,deletedAt:null},orderBy:{createdAt:'desc'},take:100})]);return NextResponse.json({supplier,products});}
export async function POST(req:Request){const u=await getActor();if(!u)return NextResponse.json({error:'UNAUTHENTICATED'},{status:401});if(u.platformRole!=='SUPPLIER'||!u.supplierId)return NextResponse.json({error:'Complete your supplier profile first'},{status:403});const parsed=item.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({error:'Enter a name, unique SKU, category, unit, nonnegative integer stock and a positive price or quote-only price.'},{status:400});const supplier=await prisma.supplier.findFirst({where:{id:u.supplierId,tenantId:u.tenantId,status:'ACTIVE',deletedAt:null},select:{id:true}});if(!supplier)return NextResponse.json({error:'Your supplier profile is not active'},{status:403});try{const product=await prisma.$transaction(async tx=>{const created=await tx.product.create({data:{...parsed.data,tenantId:u.tenantId,supplierId:supplier.id,source:'MANUAL',pricingMode:parsed.data.unitPrice===null?'RFQ':'FIXED',currency:'EGP',status:'ACTIVE'}});await appendAuditEntry({entityName:'PRODUCT',entityId:created.id,actionType:'CREATED',tenantId:u.tenantId,actorId:u.id,actorRole:u.platformRole,changes:{sku:created.sku}},tx);return created;});return NextResponse.json({product},{status:201});}catch(e){if(e instanceof Prisma.PrismaClientKnownRequestError&&e.code==='P2002')return NextResponse.json({error:'This SKU already exists. Use a unique supplier SKU.'},{status:409});throw e;}}
