import Link from "next/link";
import { ArrowRight, Eye, Search, Zap, Hotel, Store, Truck, Landmark, ShieldCheck, Activity } from "lucide-react";

const actors = [
  { title: "Hotels", text: "Turn procurement activity into evidence, savings opportunities and better buying decisions.", icon: Hotel, href: "/hotels/join" },
  { title: "Suppliers", text: "Receive relevant demand, RFQs and qualified commercial opportunities.", icon: Store, href: "/suppliers/join" },
  { title: "Carriers", text: "Participate in delivery and fulfillment opportunities across the network.", icon: Truck, href: "/carrier" },
  { title: "Funders", text: "Receive qualified funding signals while financing decisions stay external.", icon: Landmark, href: "/factoring" },
];

export default function HomePage() {
  return <main className="bg-[#f5f6f7] text-[#171a1f] dark:bg-[#0b0d10] dark:text-white">
    <section className="relative overflow-hidden bg-[#232831] px-5 pb-20 pt-32 text-white sm:px-8 lg:pb-28">
      <div className="pointer-events-none absolute inset-0 opacity-40" style={{background:"radial-gradient(circle at 70% 20%, rgba(59,130,246,.22), transparent 35%), radial-gradient(circle at 15% 80%, rgba(96,165,250,.10), transparent 30%)"}}/>
      <div className="relative mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.1fr_.9fr]">
        <div><div className="mb-5 inline-flex items-center gap-2 rounded-full border border-white/15 bg-white/5 px-3 py-1.5 text-xs font-medium text-white/70"><Activity size={14} className="text-[#60a5fa]"/> WATCH → FIND → ACT → OUTCOME</div><h1 className="max-w-4xl text-4xl font-semibold tracking-tight sm:text-5xl lg:text-6xl">Your Virtual Shadow for smarter procurement.</h1><p className="mt-6 max-w-2xl text-base leading-7 text-white/60 sm:text-lg">HotelsVendors watches authorized procurement evidence and turns it into commercial opportunities, recommended actions and measurable outcomes — across Hotels, Suppliers, Carriers and Funders.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/register" className="inline-flex items-center gap-2 rounded-lg bg-[#3b82f6] px-5 py-3 text-sm font-semibold text-white hover:bg-[#60a5fa]">Join the network <ArrowRight size={16}/></Link><Link href="/intelligence" className="rounded-lg border border-white/15 px-5 py-3 text-sm font-medium text-white/80 hover:border-[#60a5fa] hover:text-white">Explore Virtual Shadow</Link></div></div>
        <div className="relative rounded-3xl border border-white/10 bg-[#15191f] p-5 shadow-2xl"><div className="flex items-center justify-between border-b border-white/10 pb-4"><div className="flex items-center gap-2 text-sm font-semibold"><Eye size={16} className="text-[#60a5fa]"/> Virtual Shadow</div><span className="rounded-full bg-white/5 px-2.5 py-1 text-[10px] uppercase tracking-wider text-white/45">evidence-led</span></div><div className="mt-5 space-y-3"><Signal icon={Search} label="Evidence" value="Procurement activity"/><Signal icon={Zap} label="Finding" value="Potential inefficiency"/><Signal icon={ArrowRight} label="Action" value="Review supplier / quote"/><Signal icon={ShieldCheck} label="Outcome" value="Recorded only when verified"/></div><div className="mt-5 rounded-xl border border-[#3b82f6]/20 bg-[#3b82f6]/5 p-4 text-xs leading-5 text-white/55">No evidence, no claim. No human approval, no irreversible commercial action.</div></div>
      </div>
    </section>

    <section className="px-5 py-16 sm:px-8"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#3b82f6]">Four-sided network</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">One operating layer around the transaction.</h2><p className="mt-3 text-sm leading-6 text-slate-500 dark:text-slate-400">The platform is organized around the real actors and the economic loop, not a collection of disconnected features.</p></div><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-4">{actors.map(({title,text,icon:Icon,href})=><Link href={href} key={title} className="group rounded-2xl border border-slate-200 bg-white p-6 transition hover:-translate-y-0.5 hover:border-blue-400 hover:shadow-lg dark:border-slate-800 dark:bg-[#12161c]"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-200"><Icon size={19}/></div><h3 className="mt-6 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{text}</p><span className="mt-5 inline-flex items-center gap-1 text-xs font-semibold text-[#3b82f6]">Explore <ArrowRight size={13} className="transition group-hover:translate-x-1"/></span></Link>)}</div></div></section>

    <section className="bg-white px-5 py-16 sm:px-8 dark:bg-[#101318]"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#3b82f6]">Core intelligence</p><h2 className="mt-3 text-3xl font-semibold">Evidence → Opportunity → Action → Outcome</h2><p className="mt-4 text-sm leading-6 text-slate-500 dark:text-slate-400">The Virtual Shadow is useful only when the underlying business evidence is real, the action is authorized and the outcome can be measured.</p><Link href="/intelligence" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-[#3b82f6]">Open the intelligence workspace <ArrowRight size={15}/></Link></div><div className="grid gap-3 sm:grid-cols-2"><Step n="01" title="Watch" text="Invoices, orders, spend, supplier activity and authorized external signals."/><Step n="02" title="Find" text="Leaks, inefficiencies, demand matches, supplier and funding signals."/><Step n="03" title="Act" text="RFQs, supplier approaches, workflow transitions and human approvals."/><Step n="04" title="Outcome" text="Realized savings, completed transactions and traceable revenue events."/></div></div></section>

    <section className="px-5 py-16 sm:px-8"><div className="mx-auto max-w-7xl rounded-3xl bg-[#232831] p-8 text-white sm:p-12"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-center"><div><p className="text-xs font-semibold uppercase tracking-[.18em] text-[#60a5fa]">Start with real data</p><h2 className="mt-3 text-3xl font-semibold">No activity is better than fake activity.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-white/55">Connect a hotel, supplier, carrier or funder workspace. If there is not enough evidence to produce an insight, HotelsVendors shows an honest empty state.</p></div><Link href="/register" className="inline-flex items-center justify-center gap-2 rounded-lg bg-[#3b82f6] px-5 py-3 text-sm font-semibold hover:bg-[#60a5fa]">Create workspace <ArrowRight size={16}/></Link></div></div></section>
  </main>;
}
function Signal({icon:Icon,label,value}:{icon:typeof Search;label:string;value:string}){return <div className="flex items-center gap-3 rounded-xl border border-white/8 bg-white/[.03] p-3"><div className="flex h-8 w-8 items-center justify-center rounded-lg bg-white/5 text-[#60a5fa]"><Icon size={15}/></div><div><div className="text-[10px] uppercase tracking-wider text-white/35">{label}</div><div className="mt-0.5 text-sm text-white/75">{value}</div></div></div>}
function Step({n,title,text}:{n:string;title:string;text:string}){return <div className="rounded-2xl border border-slate-200 bg-[#f8f9fa] p-5 dark:border-slate-800 dark:bg-[#15191f]"><div className="text-xs font-semibold text-[#3b82f6]">{n}</div><h3 className="mt-3 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500 dark:text-slate-400">{text}</p></div>}
