"use client";
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { useAuth } from "@clerk/nextjs";
export interface CartLine { productId:string; qty:number }
export interface Toast { id:number; msg:string; tone:"ok"|"warn"|"bad" }
export interface LocalUser { id:string; name:string; email:string; role:string; platformRole:string; tenantId:string; hotelId:string|null; supplierId:string|null; factoringCompanyId:string|null }
export interface StoreShape { cart:CartLine[]; toasts:Toast[]; cartAdd:(id:string,qty?:number)=>void; cartSetQty:(id:string,qty:number)=>void; cartRemove:(id:string)=>void; cartClear:()=>void; cartCount:number; toast:(msg:string,tone?:Toast["tone"])=>void; user:LocalUser|null; data:{products:any[]}|null; logout:()=>Promise<void>; }
const Ctx=createContext<StoreShape|null>(null); const CART_KEY="hv:cart"; let toastSeq=1;
function loadCart():CartLine[]{if(typeof window==="undefined")return[];try{const x=JSON.parse(localStorage.getItem(CART_KEY)||"[]");return Array.isArray(x)?x:[]}catch{return[]}}
export function AppProvider({children}:{children:ReactNode}){const {isLoaded,isSignedIn,signOut}=useAuth();const [cart,setCart]=useState<CartLine[]>([]);const [toasts,setToasts]=useState<Toast[]>([]);const [user,setUser]=useState<LocalUser|null>(null);const [data,setData]=useState<{products:any[]}|null>(null);useEffect(()=>setCart(loadCart()),[]);useEffect(()=>{try{localStorage.setItem(CART_KEY,JSON.stringify(cart))}catch{}},[cart]);useEffect(()=>{if(!isLoaded||!isSignedIn){setUser(null);setData(null);return}let cancelled=false;(async()=>{try{const [u,p]=await Promise.all([fetch('/api/v1/me',{cache:'no-store'}),fetch('/api/v1/products?limit=100',{cache:'no-store'})]);if(!cancelled){if(u.ok){const uj=await u.json();const x=uj.data?.user;if(x){const roleMap:any={HOTEL:'hotel_admin',SUPPLIER:'supplier_manager',FACTORING:'partner_officer',SHIPPING:'carrier',ADMIN:'platform_admin',MARKETING:'hotel_admin'};setUser({...x,role:roleMap[x.platformRole]||'hotel_admin'})}}if(p.ok){const pj=await p.json();setData({products:pj.data?.products||[]})}}}catch{if(!cancelled){setUser(null);setData(null)}}})();return()=>{cancelled=true}},[isLoaded,isSignedIn]);const toast=useCallback((msg:string,tone:Toast["tone"]="ok")=>{const id=toastSeq++;setToasts(t=>[...t,{id,msg,tone}]);window.setTimeout(()=>setToasts(t=>t.filter(x=>x.id!==id)),4200)},[]);const cartAdd=useCallback((id:string,qty=1)=>setCart(c=>{const e=c.find(l=>l.productId===id);return e?c.map(l=>l.productId===id?{...l,qty:l.qty+qty}:l):[...c,{productId:id,qty}]}),[]);const cartSetQty=useCallback((id:string,qty:number)=>setCart(c=>qty<=0?c.filter(l=>l.productId!==id):c.map(l=>l.productId===id?{...l,qty}:l)),[]);const cartRemove=useCallback((id:string)=>setCart(c=>c.filter(l=>l.productId!==id)),[]);const cartClear=useCallback(()=>setCart([]),[]);const cartCount=useMemo(()=>cart.reduce((a,l)=>a+l.qty,0),[cart]);const logout=useCallback(async()=>{await signOut({redirectUrl:'/'});},[signOut]);const value=useMemo(()=>({cart,toasts,cartAdd,cartSetQty,cartRemove,cartClear,cartCount,toast,user,data,logout}),[cart,toasts,cartAdd,cartSetQty,cartRemove,cartClear,cartCount,toast,user,data,logout]);return <Ctx.Provider value={value}>{children}</Ctx.Provider>}
export function useApp(){const c=useContext(Ctx);if(!c)throw new Error('useApp must be used within AppProvider');return c}
export function ToastHost(){const {toasts}=useApp();if(!toasts.length)return null;return <div className="fixed bottom-4 right-4 z-50 flex flex-col gap-2">{toasts.map(t=><div key={t.id} className={`rounded-lg px-4 py-3 text-sm font-medium shadow-lg ${t.tone==='ok'?'bg-green-600 text-white':t.tone==='warn'?'bg-yellow-500 text-black':'bg-red-600 text-white'}`}>{t.msg}</div>)}</div>}
