
// Client-safe stub exports (no async/server-only code)
export const WebhookLogo = () => null;
export const VENDOR_SCORECARDS = [{ vendorId: 'v1', score: 95 }];
export const SapLogo = () => null;
export const RFQS = [{ id: 'r1', title: 'Sample RFQ', status: 'open' }];
export const OracleOperaLogo = () => null;
export const MicrosoftDynamicsLogo = () => null;
export const INVENTORY = [{ id: "i1", name: "Sample", quantity: 10, status: "in_stock" }];
export const PRODUCTS: any[] = [];
export const INTEGRATIONS = [{ id: "test", type: "erp", status: "connected", description: "", lastSync: "", brand: "SAP", name: "SAP" }];
export const HeroFilmNarrative = () => null;
export const DISPUTES = [{ id: 'd1', orderId: 'o1', reason: 'late', status: 'open' }];
export const CsvPortalLogo = () => null;
export const CoupaLogo = () => null;
export const CONTRACTS = [{ id: 'c1', supplier: 'Test', value: 1000, status: 'active' }];
export const evaluateAuthorityMatrix = (...args: any[]) => ({ allowed: true, reason: "" });

export const Btn = ({ children }: { children?: any }) => children || null;
export const Card = ({ children }: { children?: any }) => children || null;
export const Field = ({ children }: { children?: any }) => children || null;
export const PageHead = (p: any) => null;
export const TextInput = (p: any) => null;
export const IcScale = (p: any) => null;
export const AppShell = (p: any) => p.children || null;
export const Guard = (p: any) => p.children || null;
export const RequireAuth = (p: any) => p.children || null;
export const fmtMoney = (v: any) => String(v);
export const fmtDateTime = (v: any) => String(v);
export const fmtDate = (v: any) => String(v);
export const EmptyState = (p: any) => p.children || null;
export const Pager = (p: any) => null;
export const StatePill = (p: any) => null;
export const Stat = (p: any) => null;
export const T = (p: any) => p.children || null;
export const Td = (p: any) => p.children || null;
export const Th = (p: any) => p.children || null;
export const btnCls = () => "";
export const IcAlert = (p: any) => null;
export const IcArrow = (p: any) => null;
export const IcBox = (p: any) => null;
export const IcBuilding = (p: any) => null;
export const IcCard = (p: any) => null;
export const IcCheck = (p: any) => null;
export const IcDoc = (p: any) => null;
export const IcHand = (p: any) => null;
export const IcHistory = (p: any) => null;
export const IcInvoice = (p: any) => null;
export const IcLock = (p: any) => null;
export const IcPen = (p: any) => null;
export const IcPlus = (p: any) => null;
export const IcReceipt = (p: any) => null;
export const IcSearch = (p: any) => null;
export const IcShield = (p: any) => null;
export const IcStamp = (p: any) => null;
export const IcThermo = (p: any) => null;
export const IcTruck = (p: any) => null;
export const IcUsers = (p: any) => null;
export const IcWarehouse = (p: any) => null;
export const IcX = (p: any) => null;
export const Img = (p: any) => null;
export const Logo = (p: any) => null;
export const Modal = (p: any) => null;
export const Select = (p: any) => null;
export const Toggle = (p: any) => null;
export const TextArea = (p: any) => null;
export const useApp = () => ({ data: { stats: { totalOrders: 0, revenue: 0, pendingInvoices: 0, activeHotels: 0, supplierRating: 0 }, audit: [], orders: [], suppliers: [], hotels: [], partners: [], invoices: [], deliveries: [], inventory: [], contracts: [], disputes: [], integrations: [], rules: [], tenants: [], products: [], catalog: [], categories: [], rfqs: [], financing: [], vendors: [], logistics: [], shipments: [], payments: [], receipts: [], approvals: [], requests: [], applications: [], notifications: [], settings: {}, reports: [], analytics: {}, marketing: [] } });
export const HOTELS: any[] = [];
export const SUPPLIERS: any[] = [];
export const PARTNERS: any[] = [];
export const CARRIERS: any[] = [];
export const CATEGORIES: any[] = [];
export const USERS: any[] = [];
export const HERO_IMG = "";
export const WAREHOUSE_IMG = () => null;
export const PublicHeader = () => null;
export const getCRMDashboardStats = () => ({ totalLeads: 0, conversionRate: 0, avgDealSize: 0 });
export const hotelById = () => ({ id: "", name: "" });
export const supplierById = () => ({ id: "", name: "" });
export const partnerById = () => ({ id: "", name: "" });
export const carrierById = () => ({ id: "", name: "" });
export const productById = () => ({ id: "", name: "" });
export const integrationEngine = () => null;
export const relDay = () => 0;
export type Role = string;
export default AppShell;

export const HeroFilm = ({ children }: { children?: any }) => children || null;
export const categoryById = () => ({ id: "", name: "" });
