-- Reconcile enums required by the current procurement and ETA submission models.
DO $$ BEGIN
  CREATE TYPE "ResponseStatus" AS ENUM ('SUBMITTED', 'ACCEPTED', 'REJECTED', 'EXPIRED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE TYPE "EtaSubmissionStatus" AS ENUM ('PENDING_SUBMISSION', 'SUBMITTED', 'ACCEPTED', 'REJECTED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE TYPE "RfqStatus" AS ENUM ('DRAFT', 'OPEN', 'CLOSED', 'AWARDED', 'CANCELLED');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
ALTER TYPE "ResponseStatus" ADD VALUE IF NOT EXISTS 'SUBMITTED';
ALTER TYPE "ResponseStatus" ADD VALUE IF NOT EXISTS 'ACCEPTED';
ALTER TYPE "ResponseStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "ResponseStatus" ADD VALUE IF NOT EXISTS 'EXPIRED';
ALTER TYPE "EtaSubmissionStatus" ADD VALUE IF NOT EXISTS 'PENDING_SUBMISSION';
ALTER TYPE "EtaSubmissionStatus" ADD VALUE IF NOT EXISTS 'SUBMITTED';
ALTER TYPE "EtaSubmissionStatus" ADD VALUE IF NOT EXISTS 'ACCEPTED';
ALTER TYPE "EtaSubmissionStatus" ADD VALUE IF NOT EXISTS 'REJECTED';
ALTER TYPE "EtaSubmissionStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'DRAFT';
ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'OPEN';
ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'CLOSED';
ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'AWARDED';
ALTER TYPE "RfqStatus" ADD VALUE IF NOT EXISTS 'CANCELLED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'ACCEPTED';
ALTER TYPE "OrderStatus" ADD VALUE IF NOT EXISTS 'FULFILLED';
