import {beforeEach,describe,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({actor:vi.fn(),finding:vi.fn(),receipt:vi.fn(),change:vi.fn(),ledger:vi.fn(),audit:vi.fn(),transaction:vi.fn()}));
vi.mock('@/lib/v2-auth',()=>({getActor:m.actor}));vi.mock('@/lib/audit/tamper-proof',()=>({appendAuditEntry:m.audit}));
vi.mock('@/lib/prisma',()=>({prisma:{opportunity:{findFirst:m.finding},order:{findFirst:m.receipt},$transaction:m.transaction}}));
import {PATCH} from '@/app/api/v2/opportunities/route';
const request=(body:unknown)=>new Request('https://hotelsvendors.com/api/v2/opportunities',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
describe('received-order outcome verification',()=>{
 beforeEach(()=>{vi.resetAllMocks();m.actor.mockResolvedValue({id:'reviewer',tenantId:'own',platformRole:'HOTEL',role:'FINANCIAL_CONTROLLER'});m.finding.mockResolvedValue({id:'finding',tenantId:'own',status:'RESULT_PENDING',affectedProductId:'product',baseline:'150',createdAt:new Date('2026-10-01')});m.receipt.mockResolvedValue({id:'receipt',shippingCost:20,items:[{productId:'product',unitPrice:'100',quantity:5}]});m.change.mockResolvedValue({count:1});m.transaction.mockImplementation(fn=>fn({opportunity:{updateMany:m.change},savingsLedger:{create:m.ledger}}));});
 it('does not let ordinary buyers mark savings verified',async()=>{m.actor.mockResolvedValue({tenantId:'own',platformRole:'HOTEL',role:'DEPARTMENT_HEAD'});expect((await PATCH(request({id:'finding',status:'VERIFIED',orderId:'receipt'}))).status).toBe(403);expect(m.receipt).not.toHaveBeenCalled()});
 it('requires a later received order within the authenticated tenant',async()=>{m.receipt.mockResolvedValue(null);expect((await PATCH(request({id:'finding',status:'VERIFIED',orderId:'foreign'}))).status).toBe(409);expect(m.receipt.mock.calls[0][0].where).toMatchObject({tenantId:'own',status:'DELIVERED',currency:'EGP',createdAt:{gte:new Date('2026-10-01')}});expect(m.ledger).not.toHaveBeenCalled()});
 it('calculates savings from receipt prices, ignores browser amount, and deducts delivery cost',async()=>{expect((await PATCH(request({id:'finding',status:'VERIFIED',orderId:'receipt',realizedAmount:999999}))).status).toBe(200);expect(m.ledger.mock.calls[0][0].data).toMatchObject({tenantId:'own',realizedAmount:230,verifiedAmount:230,transactionId:'receipt',verifiedById:'reviewer'});expect(m.audit.mock.calls[0][1]).toHaveProperty('savingsLedger')});
 it('cannot create another ledger entry when the finding was concurrently closed',async()=>{m.change.mockResolvedValue({count:0});expect((await PATCH(request({id:'finding',status:'VERIFIED',orderId:'receipt'}))).status).toBe(409);expect(m.ledger).not.toHaveBeenCalled()});
 it('does not verify an order with no positive savings',async()=>{m.receipt.mockResolvedValue({id:'receipt',items:[{unitPrice:180,quantity:2}]});expect((await PATCH(request({id:'finding',status:'VERIFIED',orderId:'receipt'}))).status).toBe(409);expect(m.transaction).not.toHaveBeenCalled()});
});
