import {beforeEach,describe,expect,it,vi} from 'vitest';
const m=vi.hoisted(()=>({actor:vi.fn(),product:vi.fn(),supplier:vi.fn(),hotel:vi.fn(),createOrder:vi.fn(),orders:vi.fn(),quote:vi.fn(),rfqClaim:vi.fn(),quoteUpdate:vi.fn(),audit:vi.fn(),transaction:vi.fn(),createProduct:vi.fn(),products:vi.fn()}));
vi.mock('@/lib/auth/v2-authority',()=>({evaluateV2Authority:vi.fn()}));
vi.mock('@/lib/v2-auth',()=>({getActor:m.actor}));
vi.mock('@/lib/audit/tamper-proof',()=>({appendAuditEntry:m.audit}));
vi.mock('@/lib/prisma',()=>({prisma:{product:{findFirst:m.product,create:m.createProduct,findMany:m.products},supplier:{findFirst:m.supplier},hotel:{findFirst:m.hotel},order:{create:m.createOrder,findMany:m.orders},procurementQuote:{findFirst:m.quote},$transaction:m.transaction}}));
import {POST as createOrder,GET as getOrders} from '@/app/api/v2/orders/route';
import {POST as acceptQuote} from '@/app/api/v2/quotes/accept/route';
import {POST as publishCatalog} from '@/app/api/v2/catalog/route';
function request(body:unknown){return new Request('https://hotelsvendors.com/api/v2/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)})}
const hotelActor={id:'buyer',tenantId:'hotel-tenant',platformRole:'HOTEL',role:'DEPARTMENT_HEAD'};
describe('production procurement boundaries',()=>{
 beforeEach(()=>{vi.resetAllMocks();m.actor.mockResolvedValue(hotelActor);m.audit.mockResolvedValue({});m.transaction.mockImplementation(fn=>fn({order:{create:m.createOrder},product:{create:m.createProduct}}));m.orders.mockResolvedValue([]);m.createOrder.mockResolvedValue({id:'order',orderNumber:'HV-1'});});
 it('rejects supplier purchasing before reading products',async()=>{m.actor.mockResolvedValue({...hotelActor,platformRole:'SUPPLIER'});expect((await createOrder(request({productId:'p',supplierId:'s',quantity:2}))).status).toBe(403);expect(m.product).not.toHaveBeenCalled()});
 it('uses stored catalog price and tenant, ignoring client price/currency/tenant',async()=>{m.product.mockResolvedValue({id:'p',supplierId:'s',unitPrice:'125.50'});m.supplier.mockResolvedValue({id:'s'});m.hotel.mockResolvedValue({id:'h'});expect((await createOrder(request({productId:'p',supplierId:'s',quantity:2,unitPrice:0.01,currency:'USD',tenantId:'victim'}))).status).toBe(201);expect(m.createOrder.mock.calls[0][0].data).toMatchObject({tenantId:'hotel-tenant',currency:'EGP',subtotal:251,total:251,items:{create:{unitPrice:125.5,quantity:2}}})});
 it('suppliers see only relationship-assigned orders',async()=>{m.actor.mockResolvedValue({...hotelActor,platformRole:'SUPPLIER',supplierId:'own-supplier'});expect((await getOrders()).status).toBe(200);expect(m.orders.mock.calls[0][0].where).toEqual({supplierId:'own-supplier',deletedAt:null})});
 it('rejects quote conversion outside the authenticated hotel tenant',async()=>{m.quote.mockResolvedValue(null);expect((await acceptQuote(request({quoteId:'foreign'}))).status).toBe(404);expect(m.quote.mock.calls[0][0].where.tenantId).toBe('hotel-tenant');expect(m.transaction).not.toHaveBeenCalled()});
 it('rejects expired quote without creating an order',async()=>{m.quote.mockResolvedValue({validUntil:new Date('2020-01-01')});expect((await acceptQuote(request({quoteId:'expired'}))).status).toBe(409);expect(m.transaction).not.toHaveBeenCalled()});
 it('converts a quote atomically using stored terms',async()=>{m.quote.mockResolvedValue({id:'q',rfqId:'r',supplierId:'s',quantity:3,unitPrice:'100',deliveryFee:'25',currency:'EGP',rfq:{status:'QUOTED',tenantId:'hotel-tenant',productId:'p'}});m.hotel.mockResolvedValue({id:'h'});m.product.mockResolvedValue({id:'p'});m.rfqClaim.mockResolvedValue({count:1});m.transaction.mockImplementation(fn=>fn({rfqRequest:{updateMany:m.rfqClaim},procurementQuote:{update:m.quoteUpdate},order:{create:m.createOrder}}));expect((await acceptQuote(request({quoteId:'q',unitPrice:1,quantity:1}))).status).toBe(201);expect(m.createOrder.mock.calls[0][0].data).toMatchObject({subtotal:300,total:325,status:'PENDING_APPROVAL',items:{create:{quantity:3,unitPrice:'100'}}});expect(m.quoteUpdate).toHaveBeenCalledWith({where:{id:'q'},data:{status:'ACCEPTED'}})});
 it('rejects a competing quote conversion without creating another order',async()=>{m.quote.mockResolvedValue({id:'q',rfqId:'r',supplierId:'s',quantity:3,unitPrice:100,rfq:{status:'QUOTED',tenantId:'hotel-tenant',productId:'p'}});m.hotel.mockResolvedValue({id:'h'});m.product.mockResolvedValue({id:'p'});m.rfqClaim.mockResolvedValue({count:0});m.transaction.mockImplementation(fn=>fn({rfqRequest:{updateMany:m.rfqClaim}}));expect((await acceptQuote(request({quoteId:'q'}))).status).toBe(409);expect(m.createOrder).not.toHaveBeenCalled()});
 it('publishes catalog items with authenticated supplier identity and real provenance',async()=>{m.actor.mockResolvedValue({...hotelActor,platformRole:'SUPPLIER',supplierId:'own-supplier'});m.supplier.mockResolvedValue({id:'own-supplier'});m.createProduct.mockResolvedValue({id:'p',sku:'S-001'});expect((await publishCatalog(request({name:'Cotton towels',sku:'S-001',category:'GUEST_SUPPLIES',unitOfMeasure:'piece',unitPrice:null,stockQuantity:100,tenantId:'victim',supplierId:'other'}))).status).toBe(201);expect(m.createProduct.mock.calls[0][0].data).toMatchObject({tenantId:'hotel-tenant',supplierId:'own-supplier',source:'MANUAL',pricingMode:'RFQ'})});
});
