/**
 * evidence-chain.ts
 *
 * Explicit provenance layers for the HotelsVendors procurement economic loop.
 *
 * CORRECTION APPLIED (Correction 3 — Evidence Chain):
 * - Explicit layer hierarchy: SourceRecord → DerivedFact → Inference →
 *   CalculatedOpportunity → ScenarioHypothesis
 * - Every derived layer carries sourceIngestionId linking back to origin.
 * - Uploaded source data is FACT only as a statement about what was actually
 *   supplied/observed. Derived interpretations retain links to source records.
 *
 * EVIDENCE HIERARCHY (from Master Hermes Prompt §13):
 *   SOURCE DATA → DERIVED FACT → INFERENCE → CALCULATED OPPORTUNITY → SCENARIO/HYPOTHESIS
 *
 * NEVER convert:
 *   SCENARIO → FACT
 *   INFERENCE → FACT
 *   INDUSTRY ASSUMPTION → HOTEL EVIDENCE
 *   CALCULATED OPPORTUNITY → VERIFIED SAVING
 */

import type { CurrencyCode } from './canonical-schema';

// ─────────────────────────────────────────────────────────────────────────────
// INGESTION ID (provenance anchor)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Unique identifier for an ingestion event.
 * Generated by the ingestion API when a file is received.
 * All derived records link back to this ID.
 */
export type IngestionId = string & { __brand: 'IngestionId' };

/**
 * Create an ingestion ID from a UUID-like string.
 * In practice, this would be generated by the API layer (e.g., crypto.randomUUID()).
 */
export function createIngestionId(raw: string): IngestionId {
  return raw as IngestionId;
}

// ─────────────────────────────────────────────────────────────────────────────
// LAYER 1 — SOURCE RECORD (what was actually supplied/observed)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A record as it exists in the uploaded source file, BEFORE any normalization
 * or interpretation.
 *
 * This is FACT about what was supplied — not an interpretation.
 * If the source file says "Account 6010 has balance 50000 EGP", that is a
 * SourceRecord. It does not yet mean "this is procurement spend" — that's a
 * derived interpretation.
 */
export interface SourceRecord {
  /** Link back to the ingestion event that produced this record */
  sourceIngestionId: IngestionId;
  /** Row/index in the source file (for traceability) */
  sourceRowIndex: number;
  /** Raw field values as they appear in the source */
  rawFields: Record<string, unknown>;
  /** SHA-256 hash of the raw file content (provenance anchor) */
  rawFileHash: string;
  /** When the source file was ingested */
  ingestedAt: string;
  /** Which source system the data came from */
  sourceSystem: string;
  /** Currency of the source data (preserved, never defaulted) */
  sourceCurrency: CurrencyCode;
  /** Record count in the source file at ingestion time */
  totalSourceRecords: number;
}

// ─────────────────────────────────────────────────────────────────────────────
// LAYER 2 — DERIVED FACT (computed from source with traceability)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A fact computed directly from source records with a deterministic,
 * traceable computation.
 *
 * Example: "Account 6010 has total balance 50,000 EGP across 12 months"
 * computed by summing source records for that account.
 *
 * Every DerivedFact links to its source records via sourceIngestionId.
 * If the source data changes, the derived fact is invalidated.
 */
export interface DerivedFact {
  /** Link back to the ingestion event that is the source of this fact */
  sourceIngestionId: IngestionId;
  /** Unique ID for this derived fact */
  factId: string;
  /** Human-readable statement of what this fact asserts */
  statement: string;
  /** The computation that produced this fact (for reproducibility) */
  computation: string;
  /** The result value */
  value: number;
  /** Currency of the value */
  currency: CurrencyCode;
  /** Confidence in this derived fact (1.0 = deterministic from source) */
  confidence: number;
  /** When this fact was derived */
  derivedAt: string;
  /** List of source row indices that contributed to this fact */
  sourceRowIndices: number[];
}

// ─────────────────────────────────────────────────────────────────────────────
// LAYER 3 — INFERENCE (derived interpretation with reasoning)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * An interpretation derived from one or more DerivedFacts or SourceRecords,
 * with explicit reasoning.
 *
 * Example: "Account 6010 is procurement-relevant because it is categorized
 * as 'Food & Beverage' and its balance represents 15% of total expenses."
 *
 * Inferences are NOT facts — they are interpretations. They must be labeled
 * as such and must link back to their source evidence.
 */
export interface Inference {
  /** Link back to the ingestion event(s) that are the source of this inference */
  sourceIngestionId: IngestionId;
  /** Unique ID for this inference */
  inferenceId: string;
  /** Category of this inference (e.g., 'PROCUREMENT_RELEVANCE', 'MATERIALITY', 'CONCENTRATION') */
  category: string;
  /** Human-readable statement of what this inference asserts */
  statement: string;
  /** The reasoning that led to this inference */
  reasoning: string;
  /** Confidence in this inference (0.0–1.0) */
  confidence: number;
  /** Supporting derived facts (by factId) */
  supportingFactIds: string[];
  /** Supporting source row indices */
  supportingSourceRowIndices: number[];
  /** When this inference was made */
  inferredAt: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// LAYER 4 — CALCULATED OPPORTUNITY (baseline-proposed with evidence-backed methodology)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A quantified opportunity where the proposed value has an evidence-backed
 * calculation methodology.
 *
 * Example: "Consolidating 3 vendors for F&B supplies could save 8% based on
 * actual historical price comparison across those vendors."
 *
 * REQUIREMENT: The proposed value must have a documented methodology that
 * is backed by actual hotel evidence. If the methodology is an assumption,
 * this must be a ScenarioHypothesis, not a CalculatedOpportunity.
 *
 * CORRECTION APPLIED (Correction 4 — Savings Calculation):
 * - baseline - proposed is valid ONLY when proposed has an evidence-backed
 *   CalculationMethodology.
 * - If proposed is based on an assumption (e.g., "assume 10% discount"),
 *   this must be classified as SCENARIO/HYPOTHESIS, not savings.
 */
export interface CalculatedOpportunity {
  /** Link back to the ingestion event(s) that are the source of this opportunity */
  sourceIngestionId: IngestionId;
  /** Unique ID for this opportunity */
  opportunityId: string;
  /** Category of opportunity (e.g., 'VENDOR_CONSOLIDATION', 'PRICE_VARIANCE', 'PAYMENT_TERMS') */
  category: string;
  /** Human-readable title */
  title: string;
  /** Current state (baseline) — backed by hotel evidence */
  baseline: {
    /** Description of the current state */
    description: string;
    /** Current value */
    value: number;
    /** Currency */
    currency: CurrencyCode;
    /** Evidence supporting the baseline (source ingestion ID + fact/inference IDs) */
    evidence: EvidenceReference[];
  };
  /** Proposed state — MUST have evidence-backed methodology */
  proposed: {
    /** Description of the proposed state */
    description: string;
    /** Proposed value */
    value: number;
    /** Currency */
    currency: CurrencyCode;
    /** The calculation methodology (evidence-backed) */
    methodology: CalculationMethodology;
    /** Evidence supporting the proposed value */
    evidence: EvidenceReference[];
  };
  /** Computed saving: baseline.value - proposed.value (only valid when methodology is evidence-backed) */
  saving: number;
  /** Currency of the saving */
  savingCurrency: CurrencyCode;
  /** Confidence in this opportunity (0.0–1.0) */
  confidence: number;
  /** Implementation effort estimate (e.g., "low", "medium", "high" or a numeric estimate) */
  implementationEffort: string | number;
  /** When this opportunity was calculated */
  calculatedAt: string;
  /** Assumptions made (even evidence-backed calculations may have assumptions — list them) */
  assumptions: string[];
}

/**
 * Evidence reference: a link to a specific piece of evidence that supports
 * a claim.
 */
export interface EvidenceReference {
  /** Type of evidence: 'source_record' | 'derived_fact' | 'inference' */
  type: 'source_record' | 'derived_fact' | 'inference';
  /** ID of the evidence (sourceRowIndex, factId, or inferenceId) */
  id: string;
  /** Human-readable description of what this evidence shows */
  description: string;
}

/**
 * A calculation methodology that is backed by evidence.
 *
 * Examples:
 * - 'ACTUAL_HISTORICAL_PRICE_COMPARISON': Actual prices from hotel data compared
 * - 'ACTUAL_SUPPLIER_CONSOLIDATION': Real spend/vendor data showing consolidation opportunity
 * - 'ACTUAL_PAYMENT_TERM_ANALYSIS': Actual payment date/invoice date data
 *
 * NOT allowed as evidence-backed methodology:
 * - 'ASSUMED_DISCOUNT': "Assume suppliers give 10% discount" → SCENARIO
 * - 'INDUSTRY_AVERAGE': Industry-average discount without verified source → NOT market evidence
 */
export type CalculationMethodology =
  | 'ACTUAL_HISTORICAL_PRICE_COMPARISON'
  | 'ACTUAL_SUPPLIER_CONSOLIDATION'
  | 'ACTUAL_PAYMENT_TERM_ANALYSIS'
  | 'ACTUAL_VOLUME_MIX_ANALYSIS'
  | 'ACTUAL_CONTRACT_COMPLIANCE_CHECK'
  | 'ACTUAL_ANOMALY_DETECTION'
  | string & { __brand: 'CalculationMethodology' };

/**
 * Validate that a methodology is evidence-backed (not an assumption).
 * This is the enforcement function for Correction 4.
 */
export function isMethodologyEvidenceBacked(methodology: CalculationMethodology): boolean {
  const assumptionMethodologies = [
    'ASSUMED_DISCOUNT',
    'ASSUMED_MARKET_PRICE',
    'INDUSTRY_AVERAGE',
    'ASSUMED_VOLUME',
    'ASSUMED_TERMS',
  ];
  const upper = methodology.toUpperCase();
  return !assumptionMethodologies.some((m) => upper.includes(m));
}

// ─────────────────────────────────────────────────────────────────────────────
// LAYER 5 — SCENARIO / HYPOTHESIS (labelled assumption, not from data)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * A labelled assumption or scenario. NOT presented as a saving or market evidence.
 *
 * Example: "If suppliers offered a 10% discount on consolidated orders, the
 * hotel could save approximately 50,000 EGP annually."
 *
 * This is a SCENARIO, not a saving. The hotel has not confirmed that suppliers
 * will offer this discount.
 */
export interface ScenarioHypothesis {
  /** Link back to the ingestion event(s) that motivated this scenario */
  sourceIngestionId: IngestionId;
  /** Unique ID for this scenario */
  scenarioId: string;
  /** Type: 'SCENARIO' or 'HYPOTHESIS' */
  type: 'SCENARIO' | 'HYPOTHESIS';
  /** Human-readable description of the scenario */
  description: string;
  /** The assumption being made (must be explicit) */
  assumption: string;
  /** If the assumption were true, the projected value */
  projectedValue: number;
  /** Currency */
  projectedCurrency: CurrencyCode;
  /** Basis for the projection (what data or reasoning supports the projection, if any) */
  basis: string;
  /** Confidence in the projection (typically low, since it's an assumption) */
  confidence: number;
  /** When this scenario was created */
  createdAt: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// EVIDENCE LABEL (for findings/output)
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Evidence labeling for findings, assertions, and output.
 *
 * CORRECTION APPLIED: This matches the Master Hermes Prompt §13 evidence hierarchy.
 */
export type EvidenceLabel =
  | 'FACT'           // Directly observed in supplied data, hash-verified
  | 'DERIVED_FACT'   // Computed from source with deterministic, traceable computation
  | 'INFERENCE'      // Derived interpretation with documented reasoning
  | 'CALCULATED_OPPORTUNITY' // Baseline-proposed with evidence-backed methodology
  | 'SCENARIO'       // Labelled assumption, not from data
  | 'HYPOTHESIS';    // Labelled hypothesis, needs evidence

/**
 * Evidence label values (for runtime use — type-only imports can't use these).
 */
export const EVIDENCE_LABEL_VALUES = {
  FACT: 'FACT' as EvidenceLabel,
  DERIVED_FACT: 'DERIVED_FACT' as EvidenceLabel,
  INFERENCE: 'INFERENCE' as EvidenceLabel,
  CALCULATED_OPPORTUNITY: 'CALCULATED_OPPORTUNITY' as EvidenceLabel,
  SCENARIO: 'SCENARIO' as EvidenceLabel,
  HYPOTHESIS: 'HYPOTHESIS' as EvidenceLabel,
} as const;

/**
 * An assertion with its evidence label and provenance.
 * Used for findings output, report generation, and audit trail.
 */
export interface LabeledAssertion {
  /** Evidence label */
  evidenceLabel: EvidenceLabel;
  /** The assertion statement */
  statement: string;
  /** Source ingestion ID (where this came from) */
  sourceIngestionId: IngestionId;
  /** Supporting evidence references */
  evidence: EvidenceReference[];
  /** Confidence */
  confidence: number;
  /** When this assertion was made */
  createdAt: string;
}
