import {NextResponse} from 'next/server';
import {z} from 'zod';
import {prisma} from '@/lib/prisma';
import {getActor} from '@/lib/v2-auth';
import {appendAuditEntry} from '@/lib/audit/tamper-proof';
export async function GET(){const u=await getActor();if(!u)return NextResponse.json({error:'UNAUTHENTICATED'},{status:401});const [hotel,supplier,carrier,funder,progress]=await Promise.all([prisma.hotel.count({where:{tenantId:u.tenantId,deletedAt:null}}),prisma.supplier.count({where:{tenantId:u.tenantId,deletedAt:null}}),prisma.carrierProfile.count({where:{tenantId:u.tenantId,deletedAt:null}}),prisma.factoringCompany.count({where:{tenantId:u.tenantId,status:'ACTIVE'}}),prisma.onboardingProgress.findUnique({where:{userId:u.id}})]);const complete=u.platformRole==='HOTEL'?hotel>0:u.platformRole==='SUPPLIER'?supplier>0:u.platformRole==='SHIPPING'?carrier>0:u.platformRole==='FACTORING'?funder>0:true;return NextResponse.json({complete,platformRole:u.platformRole,tenantId:u.tenantId,resources:{hotel,supplier,carrier,funder},progress});}
export async function POST(req:Request){const u=await getActor();if(!u)return NextResponse.json({error:'UNAUTHENTICATED'},{status:401});const input=await req.json().catch(()=>null);const parsed=z.object({name:z.string().trim().min(2).max(160),taxId:z.string().trim().max(80),city:z.string().trim().min(1).max(100),governorate:z.string().trim().min(1).max(100),address:z.string().max(300).optional(),phone:z.string().max(50).optional()}).safeParse(input);if(!parsed.success)return NextResponse.json({error:'Enter valid organization details and a tax ID where required'},{status:400});const b=parsed.data;const name=String(b?.name||'').trim();const taxId=String(b?.taxId||'').trim();const city=String(b?.city||'').trim();const governorate=String(b?.governorate||'').trim();if(!name||!city||!governorate||(u.platformRole!=='SHIPPING'&&!taxId))return NextResponse.json({error:'name, city and governorate are required; taxId is required for this actor type'},{status:400});let resource:{id:string}|null=null;
 if(u.platformRole==='HOTEL'&&await prisma.hotel.findFirst({where:{tenantId:u.tenantId,deletedAt:null},select:{id:true}}))return NextResponse.json({error:'Your hotel profile is already connected. Refresh the page.'},{status:409});
 if(u.platformRole==='SUPPLIER'&&await prisma.supplier.findFirst({where:{tenantId:u.tenantId,deletedAt:null},select:{id:true}}))return NextResponse.json({error:'Your supplier profile is already connected. Refresh the page.'},{status:409});
 if(u.platformRole==='HOTEL'){resource=await prisma.hotel.create({data:{tenantId:u.tenantId,name,legalName:name,taxId,commercialReg:undefined,address:b.address||undefined,city,governorate,phone:b.phone||undefined,email:u.email,starRating:undefined,roomCount:undefined}})}
 else if(u.platformRole==='SUPPLIER'){const s=await prisma.supplier.create({data:{tenantId:u.tenantId,name,legalName:name,taxId,commercialReg:undefined,address:b.address||undefined,city,governorate,phone:b.phone||undefined,email:u.email,website:undefined,description:undefined,status:'ACTIVE',isVerified:false}});await prisma.user.update({where:{id:u.id},data:{supplierId:s.id}});resource=s}
 else if(u.platformRole==='SHIPPING'){resource=await prisma.carrierProfile.create({data:{userId:u.id,tenantId:u.tenantId,city,governorate,address:b.address||undefined,taxId:taxId||undefined,vehicleCount:1,zones:[],vehicleTypes:[],status:'PENDING_VERIFICATION'}})}
 else if(u.platformRole==='FACTORING'){resource=await prisma.factoringCompany.create({data:{tenantId:u.tenantId,name,legalName:name,taxId,status:'ACTIVE',contactEmail:u.email,contactPhone:b.phone||undefined}})}
 else return NextResponse.json({error:'Unsupported onboarding actor'},{status:400});
 const progress=await prisma.onboardingProgress.upsert({where:{userId:u.id},create:{userId:u.id,tenantId:u.tenantId,platformRole:u.platformRole,overallStatus:'COMPLETED',completedAt:new Date()},update:{overallStatus:'COMPLETED',completedAt:new Date()}});
 await appendAuditEntry({entityName:'ONBOARDING',entityId:resource!.id,actionType:'COMPLETED',tenantId:u.tenantId,actorId:u.id,actorRole:u.platformRole,changes:{actorType:u.platformRole}});
 return NextResponse.json({resource,progress},{status:201});}
