import {NextResponse} from 'next/server';
import {prisma} from '@/lib/prisma';
import {getActor} from '@/lib/v2-auth';
import {appendAuditEntry} from '@/lib/audit/tamper-proof';
export async function GET(){const u=await getActor();if(!u)return NextResponse.json({error:'UNAUTHENTICATED'},{status:401});const [hotel,supplier,carrier,funder,progress]=await Promise.all([prisma.hotel.count({where:{tenantId:u.tenantId,deletedAt:null}}),prisma.supplier.count({where:{tenantId:u.tenantId,deletedAt:null}}),prisma.carrierProfile.count({where:{tenantId:u.tenantId,deletedAt:null}}),prisma.factoringCompany.count({where:{tenantId:u.tenantId,status:'ACTIVE'}}),prisma.onboardingProgress.findUnique({where:{userId:u.id}})]);const complete=u.platformRole==='HOTEL'?hotel>0:u.platformRole==='SUPPLIER'?supplier>0:u.platformRole==='SHIPPING'?carrier>0:u.platformRole==='FACTORING'?funder>0:true;return NextResponse.json({complete,platformRole:u.platformRole,tenantId:u.tenantId,resources:{hotel,supplier,carrier,funder},progress});}
export async function POST(req:Request){const u=await getActor();if(!u)return NextResponse.json({error:'UNAUTHENTICATED'},{status:401});const b=await req.json().catch(()=>null);const name=String(b?.name||'').trim();const taxId=String(b?.taxId||'').trim();const city=String(b?.city||'').trim();const governorate=String(b?.governorate||'').trim();if(!name||!city||!governorate||(u.platformRole!=='SHIPPING'&&!taxId))return NextResponse.json({error:'name, city and governorate are required; taxId is required for this actor type'},{status:400});let resource:{id:string}|null=null;
 if(u.platformRole==='HOTEL'){resource=await prisma.hotel.create({data:{tenantId:u.tenantId,name,legalName:b.legalName||name,taxId,commercialReg:b.commercialReg||undefined,address:b.address||undefined,city,governorate,phone:b.phone||undefined,email:b.email||u.email,starRating:b.starRating?Number(b.starRating):undefined,roomCount:b.roomCount?Number(b.roomCount):undefined}})}
 else if(u.platformRole==='SUPPLIER'){const s=await prisma.supplier.create({data:{tenantId:u.tenantId,name,legalName:b.legalName||name,taxId,commercialReg:b.commercialReg||undefined,address:b.address||undefined,city,governorate,phone:b.phone||undefined,email:b.email||u.email,website:b.website||undefined,description:b.description||undefined,status:'ACTIVE',isVerified:false}});await prisma.user.update({where:{id:u.id},data:{supplierId:s.id}});resource=s}
 else if(u.platformRole==='SHIPPING'){resource=await prisma.carrierProfile.create({data:{userId:u.id,tenantId:u.tenantId,city,governorate,address:b.address||undefined,taxId:taxId||undefined,vehicleCount:b.vehicleCount?Number(b.vehicleCount):1,zones:Array.isArray(b.zones)?b.zones.map(String):[],vehicleTypes:Array.isArray(b.vehicleTypes)?b.vehicleTypes.map(String):[],status:'PENDING_VERIFICATION'}})}
 else if(u.platformRole==='FACTORING'){resource=await prisma.factoringCompany.create({data:{tenantId:u.tenantId,name,legalName:b.legalName||name,taxId,status:'ACTIVE',contactEmail:b.email||u.email,contactPhone:b.phone||undefined}})}
 else return NextResponse.json({error:'Unsupported onboarding actor'},{status:400});
 const progress=await prisma.onboardingProgress.upsert({where:{userId:u.id},create:{userId:u.id,tenantId:u.tenantId,platformRole:u.platformRole,overallStatus:'COMPLETED',completedAt:new Date()},update:{overallStatus:'COMPLETED',completedAt:new Date()}});
 await appendAuditEntry({entityName:'ONBOARDING',entityId:resource!.id,actionType:'COMPLETED',tenantId:u.tenantId,actorId:u.id,actorRole:u.platformRole,changes:{actorType:u.platformRole}});
 return NextResponse.json({resource,progress},{status:201});}
