'use client';
import {useEffect,useState,type FormEvent} from 'react';
import {requestJson} from '@/lib/v2-http';
type Entry={id:string;createdAt:string;entityName:string|null;entityId:string;actionType:string|null;actorId:string|null;actorRole:string|null;hash:string|null};
type Audit={verification:{valid:boolean;totalEntries:number}|null;entries:Entry[];nextCursor:string|null;verificationScope:string};
export function AdminClient(){
 const [data,setData]=useState<Audit|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[query,setQuery]=useState(''),[appliedQuery,setAppliedQuery]=useState('');
 async function load(q='',cursor:string|null=null,verify=false){setLoading(true);setError('');try{const p=new URLSearchParams();if(q)p.set('q',q);if(cursor)p.set('cursor',cursor);if(verify)p.set('verify','true');const result=await requestJson<Audit>('/api/v2/audit?'+p);setData(old=>({...result,entries:cursor?[...(old?.entries??[]),...result.entries]:result.entries,verification:result.verification??old?.verification??null}));setAppliedQuery(q)}catch(e){setError(e instanceof Error?e.message:'Unable to load audit records.')}finally{setLoading(false)}}
 useEffect(()=>{let cancelled=false;requestJson<Audit>('/api/v2/audit').then(result=>{if(!cancelled)setData(result)}).catch(e=>{if(!cancelled)setError(e.message)}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[]);
 function search(e:FormEvent){e.preventDefault();void load(query)}
 return <><div className="eyebrow">Administration</div><h1>Audit logs</h1><p className="muted">Read-only events from your organization. Search by entity or actor reference; other tenants’ records are excluded.</p><form onSubmit={search} className="workspace-form" style={{margin:'24px 0'}}><label>Entity or actor reference<input maxLength={100} value={query} onChange={e=>setQuery(e.target.value)}/></label><div style={{display:'flex',gap:8,alignItems:'end',flexWrap:'wrap'}}><button className="btn btn-blue" disabled={loading}>Search</button><button type="button" className="btn btn-ghost" disabled={loading} onClick={()=>load(appliedQuery,null,true)}>Verify record hashes</button></div></form>{error&&<div className="workspace-status" role="alert">{error} <button className="btn btn-ghost" disabled={loading} onClick={()=>load(appliedQuery)}>Retry</button></div>}{data?.verification&&<div className="workspace-status" role="status">{data.verification.valid?'Stored record hashes match.':'A stored record hash does not match.'} {data.verification.totalEntries} organization records checked. This does not prove global-chain completeness.</div>}<section className="card workspace-table-wrap" aria-busy={loading}>{loading&&!data?<p className="workspace-empty" role="status">Loading audit records…</p>:data?.entries.length?<table className="table"><thead><tr><th>Time</th><th>Entity / reference</th><th>Action</th><th>Actor / role</th><th>Record integrity</th></tr></thead><tbody>{data.entries.map(e=><tr key={e.id}><td>{new Date(e.createdAt).toLocaleString('en-GB')}</td><td>{e.entityName??'Record'}<br/>{e.entityId}</td><td>{e.actionType??'Not recorded'}</td><td>{e.actorId??'System'}<br/>{e.actorRole??'Not recorded'}</td><td>{e.hash?'Hash recorded':'Hash missing'}</td></tr>)}</tbody></table>:!error?<p className="workspace-empty">No audit events match this view.</p>:null}</section>{data?.nextCursor&&<button className="btn btn-ghost" style={{marginTop:16}} disabled={loading} onClick={()=>load(appliedQuery,data.nextCursor)}>{loading?'Loading…':'Load older events'}</button>}</>;
}
