'use client';
import {useEffect,useState} from 'react';
import {requestJson} from '@/lib/v2-http';
type Shipment={id:string;corridor:string;originHub:string;destinationHub:string;status:string;orderCount:number};
type Form={corridor:string;originHub:string;destinationHub:string;truckType:string};
export function CarrierConsole(){const [rows,setRows]=useState<Shipment[]>([]);const [form,setForm]=useState<Form>({corridor:'',originHub:'',destinationHub:'',truckType:'STANDARD'});const [msg,setMsg]=useState('');
 useEffect(()=>{let cancelled=false;requestJson<{shipments:Shipment[]}>('/api/v2/shipments').then(x=>{if(!cancelled)setRows(x.shipments)}).catch(e=>{if(!cancelled)setMsg(e.message)});return()=>{cancelled=true}},[]);
 async function load(){const r=await fetch('/api/v2/shipments');const x=await r.json();setRows(x.shipments||[])}
 async function create(){const r=await fetch('/api/v2/shipments',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const x=await r.json();setMsg(r.ok?'Shipment plan created.':'Unable to create: '+(x.error||'unknown'));if(r.ok)load()}
 return <div style={{marginTop:28}}><div className="card" style={{padding:22}}><div className="eyebrow">Fulfillment</div><h2 style={{margin:'10px 0'}}>Plan a shipment</h2><div style={{display:'grid',gridTemplateColumns:'repeat(2,1fr)',gap:10}}>{(['corridor','originHub','destinationHub','truckType'] as const).map(k=><input key={k} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})} placeholder={k} style={{padding:'10px 12px',border:'1px solid #d2d2d7',borderRadius:9}}/>)}</div><button className="btn btn-blue" style={{marginTop:12}} onClick={create}>Create plan</button></div>{msg&&<p style={{fontSize:13}}>{msg}</p>}<div className="card" style={{padding:22,marginTop:16}}><div className="eyebrow">Network activity</div><h2 style={{margin:'10px 0'}}>Shipments</h2>{rows.length?<table className="table"><thead><tr><th>Corridor</th><th>Route</th><th>Status</th><th>Orders</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td>{x.corridor}</td><td>{x.originHub} → {x.destinationHub}</td><td>{x.status}</td><td>{x.orderCount}</td></tr>)}</tbody></table>:<p className="muted">No shipment plans are recorded yet.</p>}</div></div>}
