'use client';
import { useEffect, useState } from 'react';
import { requestJson } from '@/lib/v2-http';
type Item={id:string;name:string;sku:string;unitPrice:string|number|null;unitOfMeasure:string};
type Catalog={supplier:{isVerified:boolean}|null;products:Item[]};
export function CatalogClient(){
 const [data,setData]=useState<Catalog|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const [form,setForm]=useState({name:'',sku:'',category:'GUEST_SUPPLIES',unitOfMeasure:'piece',unitPrice:'',stockQuantity:'0'});
 async function load(){try{setData(await requestJson<Catalog>('/api/v2/catalog'));setError('')}catch(e){setError((e as Error).message)}}
 useEffect(()=>{let active=true;requestJson<Catalog>('/api/v2/catalog').then(d=>{if(active)setData(d)}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);
 async function save(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage('');try{await requestJson('/api/v2/catalog',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...form,unitPrice:form.unitPrice?Number(form.unitPrice):null,stockQuantity:Number(form.stockQuantity)})});setMessage('Catalog item saved. Public visibility requires supplier verification.');setForm({...form,name:'',sku:'',unitPrice:''});await load()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <section className="card" style={{padding:24,marginTop:24}}><div className="eyebrow">Your supplier catalog</div><h2>Publish real supply.</h2>{error?<div role="alert">{error} <button className="btn btn-ghost" onClick={load}>Retry</button></div>:!data?<p role="status">Loading catalog…</p>:<><p className="muted">{data.supplier?.isVerified?'Your supplier profile is verified. Active items can appear in the network.':'Your profile awaits administrator verification. Items remain private until verification.'}</p><form onSubmit={save}><div className="workspace-form">{(['name','sku','unitOfMeasure','unitPrice','stockQuantity'] as const).map(k=><label key={k}>{({name:'Product name',sku:'Unique supplier SKU',unitOfMeasure:'Unit of measure',unitPrice:'Unit price · EGP (leave empty for quote only)',stockQuantity:'Stock quantity'})[k]}<input required={!['unitPrice'].includes(k)} type={['unitPrice','stockQuantity'].includes(k)?'number':'text'} min={k==='unitPrice'?'0.01':'0'} step={k==='unitPrice'?'0.01':'1'} value={form[k]} onChange={e=>setForm({...form,[k]:e.target.value})}/></label>)}<label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['F_AND_B','CONSUMABLES','GUEST_SUPPLIES','FFE','SERVICES'].map(x=><option key={x} value={x}>{x.replaceAll('_',' ')}</option>)}</select></label></div><button className="btn btn-blue" disabled={busy} style={{marginTop:18}}>{busy?'Saving…':'Save catalog item'}</button></form><div style={{overflowX:'auto',marginTop:24}}><table className="table"><thead><tr><th>Item</th><th>SKU</th><th>Price</th></tr></thead><tbody>{data.products.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.sku}</td><td>{p.unitPrice===null?'Quote only':Number(p.unitPrice).toLocaleString()+' EGP'} / {p.unitOfMeasure}</td></tr>)}</tbody></table>{!data.products.length&&<p className="muted">No catalog items yet.</p>}</div></>}{message&&<p role="status">{message}</p>}</section>;
}
