'use client';
import {useCallback,useEffect,useState} from 'react';
import {requestJson} from '@/lib/v2-http';
type FundingData={requests:Array<{id:string;status:string;requestedAmount:string|null;requestedAt:string;factoringCompanyId:string}>;companies:Array<{id:string;name:string;contactEmail:string|null}>;decisionBoundary:string};
export function FundingClient(){
 const [data,setData]=useState<FundingData|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[tab,setTab]=useState<'requests'|'partners'>('requests');
 const load=useCallback(async()=>{setLoading(true);setError('');try{setData(await requestJson<FundingData>('/api/v2/funding'));}catch(e){setError(e instanceof Error?e.message:'Unable to load funding records.');}finally{setLoading(false)}},[]);
 useEffect(()=>{let cancelled=false;Promise.resolve().then(()=>{if(!cancelled)void load()});return()=>{cancelled=true}},[load]);
 return <><div className="eyebrow">Funding workspace</div><h1>Funding records</h1><p className="muted">Review requests and partners recorded for your organization. External partners make financing decisions; this workspace does not submit or approve financing.</p><div className="workspace-tabs" role="tablist" aria-label="Funding records"><button role="tab" id="funding-requests-tab" aria-controls="funding-panel" aria-selected={tab==='requests'} onClick={()=>setTab('requests')}>Requests {data?`(${data.requests.length})`:''}</button><button role="tab" id="funding-partners-tab" aria-controls="funding-panel" aria-selected={tab==='partners'} onClick={()=>setTab('partners')}>Partners {data?`(${data.companies.length})`:''}</button></div>
 {error&&<div className="workspace-status" role="alert">{error} <button className="btn btn-ghost" onClick={load} disabled={loading}>Retry</button></div>}
 <section className="card workspace-table-wrap" role="tabpanel" id="funding-panel" aria-labelledby={`funding-${tab}-tab`} aria-busy={loading}>{loading?<p className="workspace-empty" role="status">Loading funding records…</p>:!data?null:tab==='requests'?data.requests.length?<table className="table"><thead><tr><th>Reference</th><th>Partner</th><th>Requested amount</th><th>Status</th><th>Requested</th></tr></thead><tbody>{data.requests.map(r=><tr key={r.id}><td>{r.id}</td><td>{data.companies.find(c=>c.id===r.factoringCompanyId)?.name??r.factoringCompanyId}</td><td>{r.requestedAmount===null?'Not recorded':`${Number(r.requestedAmount).toLocaleString('en-EG',{maximumFractionDigits:2})} EGP`}</td><td>{r.status.replaceAll('_',' ')}</td><td>{new Date(r.requestedAt).toLocaleDateString('en-GB')}</td></tr>)}</tbody></table>:<p className="workspace-empty">No funding requests are recorded for this organization.</p>:data.companies.length?<table className="table"><thead><tr><th>Partner</th><th>Contact</th></tr></thead><tbody>{data.companies.map(c=><tr key={c.id}><td>{c.name}</td><td>{c.contactEmail?<a href={`mailto:${c.contactEmail}`}>{c.contactEmail}</a>:'No contact recorded'}</td></tr>)}</tbody></table>:<p className="workspace-empty">No active funding partners are configured for this organization.</p>}</section><p className="muted">{data?.decisionBoundary??'External funders approve or reject financing. HotelsVendors does not lend.'}</p></>;
}
