'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {requestJson} from '@/lib/v2-http';
type Opportunity={id:string;title:string;description?:string;status:string;potentialImpact?:number|string;confidence?:number;affectedProductId?:string};
type Receipt={id:string;orderNumber:string;status:string;items:Array<{productId:string}>};
type Data={opportunities:Opportunity[];canVerifyOutcomes:boolean};
const next:Record<string,[string,string]>={DETECTED:['REVIEWING','Review finding'],REVIEWING:['ACTION_READY','Prepare action'],RESEARCHING:['ACTION_READY','Prepare action'],ACTION_READY:['APPROVED','Approve action plan'],RFQ_SENT:['APPROVED','Approve action plan'],APPROVED:['EXECUTING','Start action'],EXECUTING:['RESULT_PENDING','Review outcome']};
export function IntelligenceClient(){
 const [data,setData]=useState<Data|null>(null),[orders,setOrders]=useState<Receipt[]>([]),[selected,setSelected]=useState<Record<string,string>>({}),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const [d,o]=await Promise.all([requestJson<Data>('/api/v2/opportunities'),requestJson<{orders:Receipt[]}>('/api/v2/orders')]);setData(d);setOrders(o.orders);setError('')}
 useEffect(()=>{let active=true;Promise.all([requestJson<Data>('/api/v2/opportunities'),requestJson<{orders:Receipt[]}>('/api/v2/orders')]).then(([d,o])=>{if(active){setData(d);setOrders(o.orders)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);
 async function act(url:string,body?:object){setBusy(true);setMessage('');try{const result=await requestJson<{createdCount?:number}>(url,{method:body?'PATCH':'POST',headers:{'content-type':'application/json'},body:body?JSON.stringify(body):undefined});setMessage(body?'Outcome workflow updated.':'Scan complete: '+result.createdCount+' new findings.');await load()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <><div className="eyebrow">Market Compass</div><h1>Evidence to a measurable outcome.</h1><p className="muted">Review price variance from received orders, request a fresh quote, and record the result after delivery. Potential savings remain estimates until an authorized reviewer verifies a later received order.</p><button className="btn btn-blue" disabled={busy} onClick={()=>act('/api/v2/intelligence/scan')}>{busy?'Working…':'Scan received orders'}</button>{error?<div className="workspace-status" role="alert">{error} <button className="btn btn-ghost" onClick={()=>load().catch(e=>setError(e.message))}>Retry</button></div>:!data?<p role="status">Loading recorded findings…</p>:!data.opportunities.length?<div className="workspace-status"><h2>No findings yet.</h2><p>A price comparison needs at least two received order lines for the same product.</p><Link href="/workspace/marketplace" className="btn btn-ghost">Open procurement</Link></div>:<div className="card" style={{marginTop:24,overflowX:'auto'}}><table className="table"><thead><tr><th>Finding</th><th>Status</th><th>Potential impact</th><th>Next action</th></tr></thead><tbody>{data.opportunities.map(x=><tr key={x.id}><td><strong>{x.title}</strong><p className="muted">{x.description}</p><small>Confidence: {x.confidence?Math.round(x.confidence*100)+'%':'Unrated'}</small></td><td>{x.status.replaceAll('_',' ')}</td><td>{Number(x.potentialImpact||0).toLocaleString()} EGP · estimate</td><td>{next[x.status]&&<button className="btn btn-blue" disabled={busy} onClick={()=>act('/api/v2/opportunities',{id:x.id,status:next[x.status][0]})}>{next[x.status][1]}</button>}{['ACTION_READY','RFQ_SENT','EXECUTING'].includes(x.status)&&<p><Link href="/workspace/marketplace">Compare supplier quotes</Link></p>}{x.status==='RESULT_PENDING'&&<>{data.canVerifyOutcomes?<><label>Received order<select value={selected[x.id]||''} onChange={e=>setSelected({...selected,[x.id]:e.target.value})}><option value="">Choose an order</option>{orders.filter(o=>o.status==='DELIVERED'&&o.items.some(i=>i.productId===x.affectedProductId)).map(o=><option key={o.id} value={o.id}>{o.orderNumber}</option>)}</select></label><button className="btn btn-blue" disabled={busy||!selected[x.id]} onClick={()=>act('/api/v2/opportunities',{id:x.id,status:'VERIFIED',orderId:selected[x.id]})}>Verify received-order savings</button></>:<p>An authorized reviewer must verify the received-order outcome.</p>}<button className="btn btn-ghost" disabled={busy} onClick={()=>act('/api/v2/opportunities',{id:x.id,status:'CLOSED'})}>Close without savings</button></>}</td></tr>)}</tbody></table></div>}{message&&<p className="workspace-status" role="status">{message}</p>}</>;
}
