'use client';
import {useEffect,useState} from 'react';
import {requestJson} from '@/lib/v2-http';

type Item={id:string;quantity:number;receivedQuantity:number|null;product:{name:string;sku:string}};
type ReceiptLine={orderItemId:string;receivedQuantity:number;acceptedQuantity:number;rejectionReason:string;conditionNotes:string};
type Order={id:string;orderNumber:string;status:string;supplier?:{name:string};hotel?:{name:string};total?:number|string;currency:string;createdAt:string;allowedActions:string[];items:Item[]};
const label:Record<string,string>={APPROVED:"Approve",REJECTED:"Reject",CONFIRMED:"Confirm",IN_TRANSIT:"Mark dispatched"};

export function OrdersClient(){
 const [rows,setRows]=useState<Order[]|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[receiving,setReceiving]=useState<Order|null>(null),[lines,setLines]=useState<ReceiptLine[]>([]);
 async function refresh(){setRows((await requestJson<{orders:Order[]}>('/api/v2/orders')).orders)}
 useEffect(()=>{let cancelled=false;requestJson<{orders:Order[]}>('/api/v2/orders').then(x=>{if(!cancelled)setRows(x.orders)}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[]);
 async function advance(order:Order,status:string){setBusy(true);try{await requestJson('/api/v2/orders',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:order.id,status})});await refresh();setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function beginReceipt(order:Order){setReceiving(order);setLines(order.items.map(item=>({orderItemId:item.id,receivedQuantity:0,acceptedQuantity:0,rejectionReason:'',conditionNotes:''})))}
 async function submitReceipt(){if(!receiving)return;setBusy(true);try{await requestJson('/api/v2/grn',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({orderId:receiving.id,lines})});setReceiving(null);setError('');await refresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 function updateLine(index:number,field:keyof ReceiptLine,value:string){setLines(current=>current.map((line,i)=>i===index?{...line,[field]:field==='rejectionReason'||field==='conditionNotes'?value:Number(value),...(field==='receivedQuantity'?{acceptedQuantity:Math.min(line.acceptedQuantity,Number(value)||0)}:{})}:line))}
 return <><div className="eyebrow">Commercial activity</div><h1 style={{fontSize:42,letterSpacing:'-.05em',margin:'8px 0'}}>Orders</h1><p className="muted">Track recorded purchase orders and confirm delivery against each order line.</p><div className="card" style={{marginTop:28,overflow:'auto'}}>{error?<div className="workspace-status" role="alert">{error} <button className="btn btn-ghost" onClick={()=>window.location.reload()}>Retry</button></div>:rows===null?<div style={{padding:28}}>Loading…</div>:!rows.length?<div style={{padding:48,textAlign:'center'}}><div className="eyebrow">No orders yet</div><h2 style={{margin:'12px 0'}}>No commercial activity has been recorded.</h2></div>:<table className="table"><thead><tr><th>Order</th><th>Status</th><th>Supplier</th><th>Total</th><th>Created</th><th>Next action</th></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><strong>{x.orderNumber}</strong></td><td><span className="pill">{x.status}</span><div><small>{x.items.reduce((n,i)=>n+(i.receivedQuantity||0),0)} received across {x.items.length} lines</small></div></td><td>{x.supplier?.name||'—'}</td><td>{x.total?String(x.total)+' '+x.currency:'—'}</td><td>{new Date(x.createdAt).toLocaleDateString()}</td><td>{x.allowedActions.map(status=>status==='RECEIVE'?<button key={status} className="btn btn-ghost" disabled={busy} onClick={()=>beginReceipt(x)}>Record receipt</button>:<button key={status} className="btn btn-ghost" disabled={busy} onClick={()=>advance(x,status)}>{label[status]||status}</button>)}</td></tr>)}</tbody></table>}
 {receiving&&<section aria-label="Goods receipt" className="card" style={{padding:24,margin:18}}><div className="eyebrow">Goods received note · {receiving.orderNumber}</div><h2>Inspect delivered quantities</h2><p className="muted">Record quantities received and accepted. Rejected units need a reason. The order remains open for any outstanding quantities.</p><div style={{display:'grid',gap:14}}>{receiving.items.map((item,index)=>{const remaining=item.quantity-(item.receivedQuantity||0),line=lines[index];return <div key={item.id} style={{display:'grid',gridTemplateColumns:'minmax(160px,1fr) repeat(3,minmax(100px,150px))',gap:10,alignItems:'end',borderTop:'1px solid #ddd',paddingTop:12}}><div><strong>{item.product.name}</strong><small style={{display:'block'}}>{item.product.sku} · {remaining} remaining</small></div><label>Received<input type="number" min="0" max={remaining} step="1" value={line.receivedQuantity} onChange={e=>updateLine(index,'receivedQuantity',e.target.value)}/></label><label>Accepted<input type="number" min="0" max={line.receivedQuantity} step="1" value={line.acceptedQuantity} onChange={e=>updateLine(index,'acceptedQuantity',e.target.value)}/></label><label>Rejection reason<input value={line.rejectionReason} onChange={e=>updateLine(index,'rejectionReason',e.target.value)} placeholder="Required if rejected"/></label><label style={{gridColumn:'2 / -1'}}>Condition notes<input value={line.conditionNotes} onChange={e=>updateLine(index,'conditionNotes',e.target.value)}/></label></div>})}</div><div style={{display:'flex',gap:10,marginTop:18}}><button className="btn btn-blue" disabled={busy||lines.every(line=>line.receivedQuantity===0)} onClick={submitReceipt}>{busy?'Saving…':'Save goods receipt'}</button><button className="btn btn-ghost" disabled={busy} onClick={()=>setReceiving(null)}>Cancel</button></div></section>}
 </div></>}
}
