'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {requestJson} from '@/lib/v2-http';
type Product={id:string;name:string;sku:string;unitPrice:number|string|null;unitOfMeasure:string;supplier:{id:string;name:string;isVerified:boolean}};
type Quote={id:string;unitPrice:number|string;quantity:number;currency:string;status:string;validUntil:string|null;supplier:{name:string};rfq:{productId:string}};
export function ProcurementConsole(){
 const [products,setProducts]=useState<Product[]|null>(null),[quotes,setQuotes]=useState<Quote[]>([]),[q,setQ]=useState(''),[qty,setQty]=useState(1),[msg,setMsg]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;Promise.all([requestJson<{products:Product[]}>('/api/v2/marketplace'),requestJson<{quotes:Quote[]}>('/api/v2/quotes')]).then(([p,q])=>{if(active){setProducts(p.products);setQuotes(q.quotes)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[]);
 async function load(){setBusy(true);try{const [p,c]=await Promise.all([requestJson<{products:Product[]}>('/api/v2/marketplace?q='+encodeURIComponent(q)),requestJson<{quotes:Quote[]}>('/api/v2/quotes')]);setProducts(p.products);setQuotes(c.quotes);setError('')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 async function act(url:string,body:object,kind:'rfq'|'order'){setBusy(true);setMsg('');try{const x=await requestJson<{rfq?:{id:string};order?:{orderNumber:string}}>(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});setMsg(kind==='rfq'?'Request sent. Supplier responses appear below.':'Order '+x.order?.orderNumber+' recorded for approval.');await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}}
 return <section style={{marginTop:28}}><form className="card" onSubmit={e=>{e.preventDefault();load()}} style={{padding:18,display:'flex',gap:14,alignItems:'end',flexWrap:'wrap'}}><label style={{flex:1,minWidth:180}}>Search products<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Product name or SKU" style={{display:'block',width:'100%',padding:12,marginTop:6}}/></label><label>Quantity<input type="number" min={1} step={1} value={qty} onChange={e=>setQty(Number(e.target.value))} style={{display:'block',width:90,padding:12,marginTop:6}}/></label><button className="btn btn-blue" disabled={busy}>Search</button></form>{error&&<div className="workspace-status" role="alert">{error} <button className="btn btn-ghost" onClick={load}>Retry</button></div>}{msg&&<div className="workspace-status" role="status">{msg} <Link href="/orders">View orders</Link></div>}{!error&&products===null?<p role="status">Loading verified supply…</p>:<div className="grid3" style={{marginTop:18}}>{products?.map(p=><article className="card" style={{padding:20}} key={p.id}><span className="pill">{p.sku}</span><h3>{p.name}</h3><p className="muted">{p.supplier.name} · {p.unitOfMeasure}</p><strong>{p.unitPrice?Number(p.unitPrice).toLocaleString()+' EGP':'Quote required'}</strong><div style={{display:'flex',gap:8,marginTop:16,flexWrap:'wrap'}}><button className="btn btn-ghost" disabled={busy||!Number.isInteger(qty)||qty<1} onClick={()=>act('/api/v2/rfq',{productId:p.id,quantity:qty},'rfq')}>Request quote</button>{Number(p.unitPrice)>0&&<button className="btn btn-blue" disabled={busy||!Number.isInteger(qty)||qty<1} onClick={()=>act('/api/v2/orders',{productId:p.id,supplierId:p.supplier.id,quantity:qty},'order')}>Create order</button>}</div></article>)}</div>}{!error&&products?.length===0&&<div className="workspace-status"><h2>No verified listings match.</h2><p>Try another search. Supplier profiles must be verified before their listings are available.</p></div>}<section className="card" style={{padding:24,marginTop:24}}><h2>Supplier responses</h2><p className="muted">Review quoted prices before creating an order. An order still requires approval.</p><div style={{overflowX:'auto'}}><table className="table"><thead><tr><th>Supplier</th><th>Quantity</th><th>Unit price</th><th>Status</th><th>Action</th></tr></thead><tbody>{quotes.map(c=><tr key={c.id}><td>{c.supplier.name}</td><td>{c.quantity}</td><td>{Number(c.unitPrice).toLocaleString()} {c.currency}</td><td>{c.status}</td><td>{c.status==='SUBMITTED'&&(!c.validUntil||new Date(c.validUntil)>new Date())&&<button className="btn btn-blue" disabled={busy} onClick={()=>act('/api/v2/quotes/accept',{quoteId:c.id},'order')}>Create order from quote</button>}</td></tr>)}</tbody></table>{!quotes.length&&!error&&<p className="muted">No supplier quotes received yet.</p>}</div></section></section>;
}
