'use client';
import {useEffect,useState} from 'react';
type Product={id:string;name:string;sku:string;unitPrice:number|string|null;unitOfMeasure:string;supplier:{id:string;name:string;isVerified:boolean}};
export function ProcurementConsole(){
 const [products,setProducts]=useState<Product[]>([]);const [q,setQ]=useState('');const [qty,setQty]=useState(1);const [msg,setMsg]=useState('');
 useEffect(()=>{let cancelled=false;fetch('/api/v2/marketplace').then(r=>r.json()).then(x=>{if(!cancelled)setProducts(x.products||[])});return()=>{cancelled=true}},[]);
 async function load(){const r=await fetch('/api/v2/marketplace?q='+encodeURIComponent(q));const x=await r.json();setProducts(x.products||[])}
 async function rfq(productId:string){setMsg('Sending RFQ…');const r=await fetch('/api/v2/rfq',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({productId,quantity:qty})});const x=await r.json();setMsg(r.ok?'RFQ '+x.rfq.id+' created.':'RFQ failed: '+(x.error||'unknown error'))}
 async function order(p:Product){const r=await fetch('/api/v2/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({productId:p.id,supplierId:p.supplier.id,quantity:qty})});const x=await r.json();setMsg(r.ok?'Order '+x.order.orderNumber+' submitted for approval.':'Order failed: '+(x.error||'unknown error'))}
 return <section style={{marginTop:28}}><div className="card" style={{padding:18,display:'flex',gap:10,alignItems:'center',flexWrap:'wrap'}}><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')load()}} placeholder="Search SKU or product" style={{flex:1,minWidth:220,padding:'11px 13px',border:'1px solid #d2d2d7',borderRadius:10}}/><input type="number" min={1} value={qty} onChange={e=>setQty(Math.max(1,Number(e.target.value)||1))} style={{width:90,padding:'11px 13px',border:'1px solid #d2d2d7',borderRadius:10}}/><button className="btn btn-blue" onClick={load}>Search</button></div>{msg&&<div style={{marginTop:12,fontSize:13}}>{msg}</div>}<div className="grid3" style={{marginTop:18}}>{products.map(p=><article className="card" style={{padding:20}} key={p.id}><span className="pill">{p.sku}</span><h3 style={{margin:'12px 0 6px'}}>{p.name}</h3><p className="muted" style={{fontSize:12}}>{p.supplier.name} · {p.unitOfMeasure}</p><strong>{p.unitPrice?String(p.unitPrice)+' EGP':'Quote required'}</strong><div style={{display:'flex',gap:8,marginTop:16}}><button className="btn btn-ghost" onClick={()=>rfq(p.id)}>Request quote</button><button className="btn btn-blue" onClick={()=>order(p)}>Order</button></div></article>)}</div>{!products.length&&<div className="card" style={{padding:42,textAlign:'center',marginTop:18}}><div className="eyebrow">No verified supply</div><h2 style={{margin:'10px 0'}}>No active supplier listings match this search.</h2><p className="muted">Connect a verified supplier catalog before purchasing.</p></div>}</section>}
