'use client';
import {useEffect,useState} from 'react';
import {requestJson} from '@/lib/v2-http';
type Rfq={id:string;productId:string;requestedQty:number;status:string};type Quote={id:string};
export function SupplierConsole(){const [rfqs,setRfqs]=useState<Rfq[]>([]);const [quotes,setQuotes]=useState<Quote[]>([]);const [price,setPrice]=useState<Record<string,string>>({});const [msg,setMsg]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);
 useEffect(()=>{let cancelled=false;Promise.all([requestJson<{rfqs:Rfq[]}>('/api/v2/rfq'),requestJson<{quotes:Quote[]}>('/api/v2/quotes')]).then(([x,y])=>{if(!cancelled){setRfqs(x.rfqs);setQuotes(y.quotes)}}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[]);
 async function load(){const [x,y]=await Promise.all([requestJson<{rfqs:Rfq[]}>('/api/v2/rfq'),requestJson<{quotes:Quote[]}>('/api/v2/quotes')]);setRfqs(x.rfqs);setQuotes(y.quotes);setError('')}
 async function quote(rfq:Rfq){const p=Number(price[rfq.id]||0);if(!Number.isFinite(p)||p<=0){setMsg('Enter a valid positive unit price.');return}setBusy(true);try{await requestJson('/api/v2/quotes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({rfqId:rfq.id,unitPrice:p,quantity:rfq.requestedQty})});setMsg('Quote submitted.');await load()}catch(e){setMsg((e as Error).message)}finally{setBusy(false)}}
 return <div style={{marginTop:28}}><div className="card" style={{padding:22}}><div className="eyebrow">Demand assigned to you</div><h2 style={{margin:'10px 0'}}>Open RFQs</h2>{error&&<div role="alert">{error}</div>}{rfqs.length?<div>{rfqs.map(r=><div key={r.id} style={{padding:'16px 0',borderBottom:'1px solid #e8e8ed'}}><strong>RFQ {r.id.slice(-8)}</strong><div className="muted" style={{fontSize:12,margin:'5px 0'}}>Product {r.productId} · {r.requestedQty} units · {r.status}</div>{r.status==='PENDING'||r.status==='QUOTED'?<div style={{display:'flex',gap:8,marginTop:10}}><input type="number" min="0" aria-label={"Unit price in EGP for RFQ "+r.id.slice(-8)} placeholder="Unit price EGP" value={price[r.id]||''} onChange={e=>setPrice({...price,[r.id]:e.target.value})} style={{padding:'9px 10px',border:'1px solid #d2d2d7',borderRadius:9}}/><button className="btn btn-blue" disabled={busy} onClick={()=>quote(r)}>Submit quote</button></div>:null}</div>)}</div>:<p className="muted">No RFQs are currently assigned to this supplier.</p>}</div>{msg&&<p style={{fontSize:13,marginTop:10}}>{msg}</p>}<div className="card" style={{padding:22,marginTop:16}}><div className="eyebrow">Submitted</div><h2 style={{margin:'10px 0'}}>Quote history</h2><p className="muted">{quotes.length} quotes recorded in the network.</p></div></div>}
